# Configuration file for target cities - 50 Major US Cities

TARGET_CITIES = {
    # Top 50 US cities by population for comprehensive automotive data coverage
    "newyork": "New York, NY",
    "losangeles": "Los Angeles, CA", 
    "chicago": "Chicago, IL",
    "houston": "Houston, TX",
    "philadelphia": "Philadelphia, PA",
    "phoenix": "Phoenix, AZ",
    "sanantonio": "San Antonio, TX",
    "sandiego": "San Diego, CA",
    "dallas": "Dallas, TX",
    "miami": "Miami, FL",
    "atlanta": "Atlanta, GA",
    "boston": "Boston, MA",
    "detroit": "Detroit, MI",
    "seattle": "Seattle, WA",
    "denver": "Denver, CO",
    "lasvegas": "Las Vegas, NV",
    "portland": "Portland, OR",
    "nashville": "Nashville, TN",
    "baltimore": "Baltimore, MD",
    "milwaukee": "Milwaukee, WI",
    "albuquerque": "Albuquerque, NM",
    "tucson": "Tucson, AZ",
    "fresno": "Fresno, CA",
    "sacramento": "Sacramento, CA",
    "kansascity": "Kansas City, MO",
    "mesa": "Mesa, AZ",
    "virginiabeach": "Virginia Beach, VA",
    "omaha": "Omaha, NE",
    "colorado": "Colorado Springs, CO",
    "raleigh": "Raleigh, NC",
    "longbeach": "Long Beach, CA",
    "minneapolis": "Minneapolis, MN",
    "cleveland": "Cleveland, OH",
    "wichita": "Wichita, KS",
    "arlington": "Arlington, TX",
    "bakersfield": "Bakersfield, CA",
    "neworleans": "New Orleans, LA",
    "honolulu": "Honolulu, HI",
    "anaheim": "Anaheim, CA",
    "tampa": "Tampa, FL",
    "aurora": "Aurora, CO",
    "santaana": "Santa Ana, CA",
    "stlouis": "St. Louis, MO",
    "riverside": "Riverside, CA",
    "corpuschristi": "Corpus Christi, TX",
    "lexington": "Lexington, KY",
    "pittsburgh": "Pittsburgh, PA",
    "anchorage": "Anchorage, AK",
    "stockton": "Stockton, CA",
    "cincinnati": "Cincinnati, OH"
}

def get_target_cities():
    """Get the 50 target cities for scraping"""
    return TARGET_CITIES
